### PR TITLE
Feature: create create article API and setup logger

### PR DESCRIPTION
**Pull request by Kaidi225**
- create create article API
  - create User and Article db model
  - create a new API to create an article
- setup logger
  - add morgan to log all HTTP requests
  - add winston to log system logs

### CODE REVIEW

**Comment by kunjanvaghela** [comment]
@Kaidi225 can you resolve the conflicting file: `backend/src/controllers/articleController.js`

**Comment by Kaidi225** [comment]
> @Kaidi225 can you resolve the conflicting file: `backend/src/controllers/articleController.js`

@kunjanvaghela We wrote our own versions from scratch, and it is hard to resolve the conflicts. I'm planning to overwrite the entire file or even the whole commits since I'm responsible for the article management section. What do you think?

**Comment by kunjanvaghela** [comment]
I see that @sahithir27 made the initial changes, can you @Kaidi225 check with her so that her work is not lost?

**Comment by Kaidi225** [comment]
> I see that @sahithir27 made the initial changes, can you @Kaidi225 check with her so that her work is not lost?

@kunjanvaghela I had actually created my PR earlier and posted it in the group chat, and I’m responsible for the article management section.
Although the conflicts only happens in this file, actually there are more overlapping works. My and her versions of this files depends on different models and are used by different routers. Unfortunately, there are so many overlaps and conflicts, and I think someone's work have to be discarded.Forcefully merging the two versions is no simpler than rewriting the non-overlapping parts from scratch.
cc @sahithir27

**Comment by Kaidi225** [comment]
@kunjanvaghela @sahithir27 I have resolved the conflicts and integrated Sahithi's work. Please review, thanks!

**Pull request merged**
